MTV/urls.py
from django.urls import path
from . import views

app_name = 'MTV'

urlpatterns = [

path('', views.BoardList.as_view(), name= 'index'),
path('upload/', views.Upload.as_view(), name='upload'),
path('delete/<int:pk>/', views.BoardDelete, name='delete'),
path('<int:pk>/',views.Get.as_view(), name='get'),
path('comment/<int:document_id>/', views.document_detail, name="comment"),
path('comment/delete/<int:comment_id>/', views.comment_delete, name="comment_delete"),
path('result/', views.result, name='result')

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name= 'common/login.html'), name= 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from MTV import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('MTV/',include('MTV.urls')),
    path('', views.BoardList.as_view(),name='index'),
    path('common/',include('common.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MTV/models.py
from email.mime import image
from tkinter import image_types
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
import os

class Board(models.Model) :
    title = models.CharField(max_length=100)
    content = models.TextField()
    sound = models.FileField(blank= True, null = True, upload_to = 'blog_sound') 
    photo = models.ImageField(blank= True, null = True, upload_to = 'blog_photo') 
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add = True)
    modify_date = models.DateTimeField(auto_now= True, null=True, blank=True)
    
    def __str__(self) :
            return f'[PK:{self.pk}]-{self.title} :: {self.author}'


    def get_FileName(self) :
        return os.path.basename(self.sound.name)

    def get_ImageName(self) :
        return os.path.basename(self.photo.name)

    def get_absolute_url(self) :
        return f'/MTV/{self.pk}'




class Comment(models.Model):
    document = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)

    def __str__(self):
        return (self.author.username if self.author else "무명")+ "의 댓글"
        

MTV/forms.py
from django import forms
from .models import Board, Comment
from django.utils.safestring import mark_safe

class BoardCreateForm(forms.ModelForm) :
    
    def __init__(self, *args, **kwargs) :
        super().__init__(*args,**kwargs) 
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['sound'].widget.attrs.update({'class': 'form-control'})
        self.fields['photo'].widget.attrs.update({'class': 'form-control'})
        self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
        
        
        

    class Meta :
        model = Board
        fields = ('title','sound', 'photo', 'content',)




class CustomFileWidget(forms.FileInput):
    def __init__(self, attrs={}):
        super().__init__(attrs)

    def render(self, name, value, attrs=None, renderer=None):
        output = []
        if value and hasattr(value, "url"):
            file_name = value.url.split('/')[-1]
            output.append(super().render(name, value, attrs))
            output.append(f'<span class="form-control">첨부파일 : <a class="text-reset text-decoration-none" target="_blank" href="{value.url}">{file_name}</a><input class="form-check-input ms-2 me-1" type="checkbox" name="upload_clear" id="upload_clear_id" value="upload_del">Delete</span>')
            return mark_safe(u''.join(output))
        output.append(super().render(name, value, attrs))
        return mark_safe(u''.join(output))


class CommentForm(forms.ModelForm):
    #text = forms.TextInput(label = '댓글')

    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = "댓글"

MTV/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib import messages
from MTV.models import Board, Comment
from django.views.generic import DetailView, ListView,CreateView, UpdateView, DeleteView
from MTV.forms import BoardCreateForm,CommentForm
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
import os, time
from config import settings
from MTV.models import Board
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request) :
    return render (request, 'MTV/index.html')


def subscribe(request) :
    return render (request, 'MTV/subscribe.html')

class BoardList(ListView):
    model = Board
    template_name = 'MTV/index.html'
    ordering = '-pk'
    paginate_by = 6

class Upload(CreateView) :
    model = Board
    form_class = BoardCreateForm
    template_name = 'MTV/upload.html'
    def form_valid(self, form) :
        current_user = self.request.user
        if current_user.is_authenticated :
            form.instance.author = current_user
            return super().form_valid(form)
        else :
            return redirect('/')

@login_required(login_url='common:login')
def BoardDelete(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.user != board.author:
        return redirect('MTV:get', pk=pk)
    if board.sound:
        sound_path = os.path.join(settings.MEDIA_ROOT, board.sound.path)
        if os.path.exists(sound_path):
            os.remove(sound_path)
    if board.photo:
        photo_path = os.path.join(settings.MEDIA_ROOT, board.photo.path)
        if os.path.exists(photo_path):
            os.remove(photo_path)
    board.delete()
    return redirect('MTV:index')

class Get(DetailView) :
    model = Board
    template_name = 'MTV/get.html'


                                                                                       



def document_detail(request, document_id):
    
    document = get_object_or_404(Board, pk=document_id)

    #만약 post일때만 댓글 입력에 관한 처리를 더한다.

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        comment_form.instance.author_id = request.user.id
        comment_form.instance.document_id = document_id
        if comment_form.is_valid():
            comment = comment_form.save()


    #models.py에서 document의 related_name을 comments로 해놓았다.

    comment_form = CommentForm()
    comments = document.comments.all()

    return render(request, 'MTV/comment.html', {'object':document, "comments":comments, "comment_form":comment_form})




def comment_update(request, comment_id):
    
    comment = get_object_or_404(Comment, pk=comment_id)
    document = get_object_or_404(Board, pk=comment.document.id)

    if request.user != comment.author:
        messages.warning(request, "권한 없음")
        return redirect(document)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(document)
    else:
        form = CommentForm(instance=comment)
        return render(request,'MTV/comment_update.html',{'form':form})


def comment_delete(request, comment_id):

    comment = get_object_or_404(Comment, pk=comment_id)
    document = get_object_or_404(Board, pk=comment.document.id)

    if request.user != comment.author and not request.user.is_staff and request.user != document.author:
        messages.warning(request, '권한 없음')
        return redirect(document)
    if request.method == "POST":
        comment.delete()
        return redirect(document)
    else:
        return render(request, 'MTV/comment_delete.html', {'object':comment})


@login_required(login_url='common:login')
def result(request): 
    posts= Board.objects.all()
    start= time.time()
    query = request.GET['query']
    if query :
        posts= Board.objects.filter(title__contains=query)
        end= time.time() - start 
    return render(request, 'MTV/result.html', {'posts':posts, 'time':end})

templates/MTV/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>PigmaMusichhhhh ㅗㅗㅗㅗ마지막테스트</title>

 <!-- Bootstrap CDN URL -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  <!-- Fontawesome URL -->
  <script src="https://kit.fontawesome.com/53e4af2e34.js" crossorigin="anonymous"></script>


    <!-- Jquery CDN URL -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    
    
    <!-- Custom styles for this template -->
  
    
   </head>
   <body>
    {% include "MTV/navbar.html" %}
    {% include 'MTV/frontboard.html'%}

    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}

    {% include 'MTV/footer.html' %}
    </body>
    
    </html>

templates/MTV/base_get.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Headers · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/headers/">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/footers/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Jquery CDN URL -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    
    
    <!-- Custom styles for this template -->
  
    
   </head>
   <body>
    {% include "MTV/navbar.html" %}
    

    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}

    {% include 'MTV/footer.html' %}
    </body>
    
    </html>

templates/MTV/comment.html
<form action="{% url 'MTV:comment' object.id %}" method="POST">
{% csrf_token %}

    {{ comment_form.as_p }}
    <input type="submit" value="Comment" class="btn btn-outline-primary">

</form>

{% for comment in comments %}


<div class="card text-bg-primary" style="max-width: 50rem;">
    <div class="card-header">
        
        
        <p>작성자 : {{ comment.author.username }}</p>
        
       
    <p>생성일 : {{ comment.created }}</p>
        
</div>
    <div class="card-body">
      <p class="card-text">{{ comment.text }}</p>
      {% if user == comment.author %}
      <td class="text-bottom"><a href="{% url 'MTV:comment_delete' comment.id %}">삭제하기</a></td>
      {% else %}
      <td class="text-bottom"><a href="#" onclick="alert('삭제 권한이 없습니다.')">삭제하기</a></td>
      {% endif %}

    </div>

{% endfor %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% block content %}
{% endblock %}

templates/MTV/comment_delete.html
{% block content %}
<!--진짜 지울건지 확인을 받아야 한다. form을 또 보여줄 필요가 없다.-->
<div class="alert alert-primary" role="alert">
  진짜로 {{object}}를 지우실 건가요?
</div>
<form action="" method ="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

templates/MTV/comment_update.html
{% extends 'MTV/comment.html' %}

{% block content %}

<form action="" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
        </table>
    <input type="submit" value="Write">

</form>

{% endblock %}

templates/MTV/footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-muted">&copy; 2022 PigmaMusic, Inc</p>
  
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
  
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
    </footer>
  </div>

templates/MTV/frontboard.html
{% load static %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <img src="{% static 'pigmamusic.png' %}" class="img-fluid  col-12 ">
        <span>
        <h1 class="fw-light">Connect on PigmaMusic</h1>
        <p class="lead text-muted">Discover, stream, and share a constantly expanding mix of music from emerging and major artists around the world.</p>
        {% if user.is_anonymous %}
        <p>
          <a href="#" class="login_check btn btn-secondary my-2">클라우드에 업로드하기 !</a>
        </p>
        {% else %}
          <p>
            <a href="{% url 'MTV:upload' %}" class="btn btn-secondary my-2">클라우드에 업로드하기!</a>
          </p>
        </span>
        {% endif %}

      </div>
      <div>
      <form login_check class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'MTV:result' %}" method='GET' >
        {% csrf_token %}
        
        <input login_check type="search" class="form-control form-control-dark text-bg-dark" placeholder="게시글 검색하기..." name="query">
        <input login_check type="submit" value="검색" >

      </form>
      {% block content %}
      {% endblock %}

    </div>
    </div>
  </section>



  

templates/MTV/get.html
{% extends 'MTV/base_get.html' %}

{% block content %}

<section class="py-5 text-center container"></section>



  <section class="board_detail-block">
    <div class="container mt-3">
    <div class="card border-dark mb-3">
      <div class="card-header">
        <h4 class="pt-1">{{ object.title }}</h4>
        {% if object.modify_date %}
        <p class="pt-1">Created by {{ object.author }} on {{ object.modify_date }}</p>
        {% else %}
        <p class="pt-1">Created by {{ object.author }} on {{ object.create_date }}</p>
        {% endif %}
      </div>


      <div class="card-body text-dark">
        <p class="card-text">{{ object.content | linebreaksbr }}</p>
        <div class="image-box">

        <span>
          <audio class="sound mt-4" controls>
              <source src="https://pigmamusic.s3.ap-northeast-2.amazonaws.com/{{ object.sound }}" type="audio/mp3">
          </audio>
        </span>
      </div>
        <div class="mt-4">

        </div>
      </div>
      <div class="card-footer d-flex justify-content-between">
        <a href="/" class="btn btn-outline-dark">목록</a>
        
        {% if user == object.author %}
        <span>
          <a href="#" class="btn btn-outline-dark">수정</a>
          <a href="#" class="delete btn btn-outline-dark" data-uri="{% url 'MTV:delete' object.id %} " >삭제</a>
        </span>
        {% else %}
        <span>
          <a href="#" class="user_check btn btn-outline-dark">수정</a>
          <a href="#" class="user_check btn btn-outline-dark">삭제</a>
        </span>
        {% endif %}
      </div>
        
    </div>
    {% include 'MTV/comment.html' %}
    </div>
    
  </section>


{% endblock %}

{% block script %}
<script type='text/javascript'>
  $(document).ready(function() {
    $(".delete").on('click', function() {
      if(confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data('uri');
      }
    });
  });

  $(document).ready(function() {
    $(".user_check").on('click', function() {
      alert("자신의 게시글만 수정 및 삭제가 가능합니다.")
    });
  });
</script>
{% endblock %}

templates/MTV/index.html
{% extends "MTV/base.html" %}
{% load static %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
     
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">     
      {% for board in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            {% if user.is_anonymous %}
            <a href="{{ board.get_absolute_url }}"  rel="noopener" class= "login_check" >
              
                <img  width="100%" height="225" class="Thumbnail" src="https://pigmamusic.s3.ap-northeast-2.amazonaws.com/{{ board.photo }}">
              
            </a>
            {% else %}
            <a href="{{ board.get_absolute_url }}"  target="_blank" rel="noopener" >
              
              <img  width="100%" height="225" class="Thumbnail" src="https://pigmamusic.s3.ap-northeast-2.amazonaws.com/{{ board.photo }}">
            
          </a>
          {% endif %}
            </div>
            <div class="card-body">
              <div>
              <small class="text-muted "> {{ board.title }}</small>
            </div>
              <small class="text-muted "> 생성자 : {{ board.author }}</small>
              <div class="description">
                
              </div>    
              <div class=" align-items-center">
                <div class="btn-group">
                  {% if user.is_anonymous %}
                  <button type="button" class=" login_check btn btn-sm btn-outline-secondary">
                    게시글 보기</button>
                    <small class="text-end">{{ board.modify_date }}</small>
                    {% else %}
                    <button type="button" class=" btn btn-sm btn-outline-secondary" onclick="window.location.href='{{ board.get_absolute_url }}'">
                      게시글 보기</button>
                <small class="text-end">{{ board.modify_date }}</small>
                {% endif %}
              </div>
              
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
</div>
</div>


    <!-- pagination 영역 -->



    {% if page_obj.paginator.count >= page_obj.paginator.per_page %}

    <ul class="pagination justify-content-center">
      
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">이전</a>
      </li>
      {% endif %}

    
      {% for page_number in page_obj.paginator.page_range %}
      {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
        {% if page_number == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link"  href="?page={{ page_obj.next_page_number }}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">다음</a>
      </li>
      {% endif %}

    </ul>
    {% endif %}
  </div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
  $(document).ready(function() {
    $(".login_check").on('click', function() {
      alert("로그인 후 이용이 가능합니다.")
    });
  });
</script>
{% endblock %}

templates/MTV/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light border-bottom">
    <div class="container-fluid">
          <!-- Logo 영역 -->
    <a class="mb-2 navbar-brand" href="/"><img src="{% static 'pigmamusic.png' %}" width="70" height="50" alt=""> </a>

        <a class="navbar-brand" href="{% url 'MTV:index' %}"><h1> PigmaMusic </h1></a> 
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

        </div>
  

       
          <div class="text-end">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_anonymous %}
            <a class="nav-link" href="{% url 'common:login' %}"><i class="fa-solid fa-user me-2"></i>로그인</a>
            <a class="nav-link" href="{% url 'common:signup' %}"><i class="fa-solid fa-user me-2"></i>회원가입</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:logout' %}"><i class="fa-solid fa-user me-2"></i>로그아웃 [ {{ user.username }} ]</a>
          
            {% endif %}
              </ul>
          </div>

        </div>
      </div>
    </div>
  </nav>

templates/MTV/result.html
{% extends 'MTV/index.html' %}
{% load static %}
{% block content %}


<h4> 게시글 검색 시간 : {{ time }} </h4>
<div class="album py-5 bg-light">
    <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">   
{% for post in posts %}
<div class="col">
    <div class="card shadow-sm">
      {% if user.is_anonymous %}
      <a href="#"  rel="noopener" class= "login_check" >
        
          <img alt="{{ post.title }}" width="100%" height="225" class="Thumbnail" src="https://pigmamusic.s3.ap-northeast-2.amazonaws.com/{{ post.photo }}">
        
      </a>
      {% else %}
      <a href="{{ post.content }}"  target="_blank" rel="noopener" >
        
        <img alt="{{ post.title }}" width="100%" height="225" class="Thumbnail" src="https://pigmamusic.s3.ap-northeast-2.amazonaws.com/{{ post.photo }}">
      
    </a>
    {% endif %}
      </div>
      <div class="card-body">
        <div>
        <small class="text-muted "> {{ post.title }}</small>
      </div>
        <small class="text-muted "> 생성자 : {{ post.author }}</small>
        <div class="description">
          
        </div>    
        <div class=" align-items-center">
          <div class="btn-group">
            {% if user.is_anonymous %}
            <button type="button" class=" login_check btn btn-sm btn-outline-secondary">
              게시글 보기</button>
              <small class="text-end">{{ post.modify_date }}</small>
              {% else %}
              <button type="button" class=" btn btn-sm btn-outline-secondary" onclick="window.location.href='{{ board.get_absolute_url }}'">
                게시글 보기</button>
          <small class="text-end">{{ post.modify_date }}</small>
          {% endif %}
        </div>
        
      </div>
    </div>
  </div>
  {% endfor %}

 <!-- pagination 영역 -->



 {% if page_obj.paginator.count >= page_obj.paginator.per_page %}

 <ul class="pagination justify-content-center">
   
   {% if page_obj.has_previous %}
   <li class="page-item">
     <a class="page-link" href="?page={{page_obj.previous_page_number}}">이전</a>
   </li>
   {% else %}
   <li class="page-item disabled">
     <a class="page-link">이전</a>
   </li>
   {% endif %}

 
   {% for page_number in page_obj.paginator.page_range %}
   {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
     {% if page_number == page_obj.number %}
       <li class="page-item active">
         <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
       </li>
     {% else %}
       <li class="page-item">
         <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
       </li>
     {% endif %}
   {% endif %}
   {% endfor %}

{% if page_obj.has_next %}
   <li class="page-item">
     <a class="page-link"  href="?page={{ page_obj.next_page_number }}">다음</a>
   </li>
   {% else %}
   <li class="page-item disabled">
     <a class="page-link">다음</a>
   </li>
   {% endif %}

 </ul>
 {% endif %}
</div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function() {
 $(".login_check").on('click', function() {
   alert("로그인 후 이용이 가능합니다.")
 });
});
</script>
{% endblock %}

templates/MTV/upload.html
{% extends "MTV/base.html" %}
{% block content %}
  <section class="board_form-block">
  <div class="container mt-3">
    <form method="post" enctype="multipart/form-data"> 
      {% csrf_token %}
      <div class="card">
        <div class="card-header input-group">
          <span class="input-group-text">제목 입력</span>
          {{ form.title }}
        </div>
        
        <div class="card-header input-group">
          <span class="input-group-text">사진 등록</span>
          {{ form.photo }}
        </div>
        <div class="card-header input-group">
          <span class="input-group-text">음악 등록</span>
          {{ form.sound }}
        </div>
        <div class="card-body">
          <span class="input-group-text">게시글 입력</span>
          {{ form.content }}
        </div>
        <button type="submit" class="btn btn-outline-dark">게시글 등록</button>
      </div>
    </form>
  </div>
  </section>
{% endblock %}