MTV/urls.py
from django.urls import path
from . import views

app_name = 'MTV'

urlpatterns = [

path('', views.BoardList.as_view(), name= 'index'),
path('upload/', views.Upload.as_view(), name='upload'),
path('delete/<int:pk>/', views.BoardDelete, name='delete'),
path('<int:pk>/',views.Get.as_view(), name='get'),
path('comment/<int:document_id>/', views.document_detail, name="comment"),
path('comment/delete/<int:comment_id>/', views.comment_delete, name="comment_delete"),
path('result/', views.result, name='result')

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name= 'common/login.html'), name= 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from MTV import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('MTV/',include('MTV.urls')),
    path('', views.BoardList.as_view(),name='index'),
    path('common/',include('common.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
  if request.method == "POST":
    form = UserForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=raw_password)
      login(request, user)
      return redirect('/')
  else:
      form = UserForm()
  return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends "MTV/base.html" %}
{% block content %}
  <section class="login-block">
  <div class="container">
    <div class="row">
      <div class="card col-lg-4">
        <div class="card-body">
          <h1 class="text-center mt-4 mb-5">LOGIN</h1>

          <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <div class="input-group mb-4">
              <input type="text" class="form-control" name="username" id="username" placeholder="Enter User ID" value="{{ form.username.value | default_if_none:'' }}">
            </div>

            <div class="input-group mb-3">
              <input type="password" class="form-control" name="password" id="password" placeholder="Enter User Password" value="{{ form.password.value | default_if_none:'' }}">
            </div>

            <div class="d-grid gap-1">
              <button type="submit" class="btn btn-outline-dark mt-4">로그인</button>
            </div>
          </form>


        </div>
        <div class="card-footer text-muted text-center">
          <i class="fs-2 mx-2 fa-brands fa-instagram-square"></i>
          <i class="fs-2 mx-2 fa-brands fa-facebook-square"></i>
          <i class="fs-2 mx-2 fa-brands fa-google"></i>
          <i class="fs-2 mx-2 fa-brands fa-apple"></i>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card">
          <img class="card-img-top" src="https://static.pexels.com/photos/33972/pexels-photo.jpg" alt="...">
        </div>
      </div> 
    </div>
  </div>
  </section>
  {% endblock %}

templates/common/signup.html
{% extends "MTV/base.html" %}
{% block content %}

  <section class="signup-block">
    <div class="container">
      <div class="row">
        <div class="card col-lg-4">
          <div class="card-body">
            <h1 class="text-center mt-2 mb-5">SIGNUP</h1>
            <form method="POST" class="post-form" action="{% url 'common:signup' %}">
              {% csrf_token %}
              
              {% include 'form_errors.html' %}
              <div class="input-group mb-4">
                <input type="text" class="form-control" name="username" id="username" placeholder="ID" value="{{ form.username.value|default_if_none:'' }}">
              </div>
              <div class="input-group mb-4">
                <input type="password" class="form-control" name="password1" id="password1" placeholder="Password" value="{{ form.password1.value|default_if_none:'' }}">
              </div>
              <div class="input-group mb-4">
                <input type="password" class="form-control" name="password2" id="password2" placeholder="Re-Entry Password" value="{{ form.password2.value|default_if_none:'' }}">
              </div>
              <div class="input-group mb-4">
                <input type="email" class="form-control" name="email" id="email" placeholder="E-mail Address" value="{{ form.email.value|default_if_none:'' }}">
              </div>
  
              <div class="d-grid gap-1">
                <button type="submit" class="btn btn-outline-dark mt-2">회원가입</button>
                <button type="reset" class="btn btn-outline-dark mt-2">취소</button>
              </div>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            <i class="fs-2 mx-2 fa-brands fa-instagram-square"></i>
            <i class="fs-2 mx-2 fa-brands fa-facebook-square"></i>
            <i class="fs-2 mx-2 fa-brands fa-google"></i>
            <i class="fs-2 mx-2 fa-brands fa-apple"></i>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card">
            <img class="card-img-top" src="https://static.pexels.com/photos/33972/pexels-photo.jpg" alt="...">
          </div>
        </div> 
      </div>
    </div>
    </section>
    {% endblock %}